name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    services:
      postgres:
        image: postgres:latest
        
        env:
          POSTGRES_DB: users
          POSTGRES_PASSWORD: asisipho123
          POSTGRES_PORT: 5432
          POSTGRES_USER: asisipho
        ports:
          - 5432:5432
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        PGPASSWORD: asisipho123
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g npm
    - run: npm install
    - run: |
        PGPASSWORD=asisipho123 psql -h localhost -U asisipho -d users
        PGPASSWORD=asisipho123 psql -h localhost -U asisipho -d users 
    - run: npm run build --if-present
    - run: npm test
      env: 
        DATABASE_URL: postgresql://asisipho:asisipho123@localhost:5432/users
